# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea7cd3bfa9ca8295d29710981cfe0606f03dd17a9714f716024e112b42740a7adb67c36a4c7a5c98526540c9ab444c565512d4355cc766ef9db253dd97cb7365

test:
  secret_key_base: 3a37952c27dbc42ca5de4c0005a3109aadf61bf202247c2404fde5d72898063227e25c4c18bca74ac0b4b95edc5c08642a1efa5eeb6c69fa1cc4e6d98dde78da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
